// <auto-generated />
namespace XGame.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class GameMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GameMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "202002131524457_GameMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
